server:
  port: 8095

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: Timed Event Service
    main:
      allow-bean-definition-overriding: true
  jackson.date-format: yyyy-MM-dd
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${IDAM_URL:http://127.0.0.1:5000}/o
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:ia}
            client-secret: ${IA_IDAM_SECRET:something}
      resourceserver:
        jwt:
          jwk-set-uri: ${IDAM_URL:http://127.0.0.1:5000}/o/jwks

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"
    - "/csrf"
  authorisedServices:
    - "iac"
  roleEventAccess:
    caseworker-ia-caseofficer:
    - "unknown"

auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:4502}
