server:
  port: 8095

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: Timed Event Service
  main:
    allow-bean-definition-overriding: true
  jackson.date-format: yyyy-MM-dd
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${IDAM_URL:http://127.0.0.1:5000}/o
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:ia}
            client-secret: ${IA_IDAM_SECRET:something}
      resourceserver:
        jwt:
          jwk-set-uri: ${IDAM_URL:http://127.0.0.1:5000}/o/jwks
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: timed-event-quartz-scheduler
            instanceId: AUTO

retry:
  durationInSeconds: ${IA_SCHEDULER_RETRY_DURATION:1800}
  maxRetryNumber: ${IA_SCHEDULER_MAX_RETRY_NUMBER:50}

health:
  services:
    idam:
      uri: ${IDAM_URL:http://127.0.0.1:5000}/health
      response: '"status":"UP"'
    serviceAuth:
      uri: ${S2S_URL:http://127.0.0.1:4502}/health
      response: '"status":"UP"'
    ccd:
      uri: ${CCD_URL:http://127.0.0.1:4452}/health
      response: '"status":"UP"'

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"
    - "/csrf"
    - "/testing-support/**"
  roleEventAccess:
    caseworker-ia-caseofficer:
    - "requestHearingRequirementsFeature"
    - "example"
    - "unknown"

auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:4502}

idam:
  baseUrl: ${IDAM_URL:http://127.0.0.1:5000}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  system:
    username: ${IA_SYSTEM_USERNAME:ia-system-user@fake.hmcts.net}
    password: ${IA_SYSTEM_PASSWORD:London05}
    scope: "openid profile roles"
  s2s-auth:
    totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IA_S2S_MICROSERVICE:ia}
    url: ${S2S_URL:http://127.0.0.1:4502}
  s2s-authorised:
    services: ${IA_S2S_AUTHORIZED_SERVICES:iac}

ccd:
  case-data-api:
    url: ${CCD_URL:http://127.0.0.1:4452}