java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_URL: "https://ccd-data-store-api-ia-case-api-pr-1963.preview.platform.hmcts.net"
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    POSTGRES_CONNECTION_OPTIONS: ""
  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - idam-client-id
        - idam-secret
        - idam-redirect-uri
        - system-username
        - system-password
        - s2s-secret
        - s2s-microservice
        - AppInsightsInstrumentationKey
        - app-insights-connection-string
        - ia-config-validator-secret
  postgresql:
    enabled: true